---
abstract: ~
author:
  - 'Ingy döt Net <ingy@cpan.org>'
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: YAML-LibYAML
no_index:
  directory:
    - inc
    - t
requires:
  Filter::Util::Call: 0
  perl: 5.8.3
resources:
  license: http://dev.perl.org/licenses/
version: 0.30
